# Generated by Django 4.2 on 2023-04-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_company_address_alter_company_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
